### PR TITLE
Add a LICENSE

### PR DESCRIPTION
**Pull request by axiliquint**
Added the Unlisence - see more info here https://choosealicense.com/licenses/

*contributed on behalf of Koal OSS*

### CODE REVIEW

**Comment by realgavinmartin** [comment]
This isn't open source software and the creators have been reported already. We kindly request this isn't merged. :)

**Comment by axiliquint** [comment]
ratio + didnt ask

**Comment by kvyuaiss** [comment]
This contains copyright material and isn’t the property of Luke Harland, it falls under Gavin Martin and Eastside Online Services, ratio that

**Comment by callumisdumb** [comment]
@axiliquint you arent allowed to ratio anyone when you use nuxt.js and vue
see attached: https://github.com/axiliquint/axiliquint

**Review by lukeharlandd — APPROVED** [review]

**Review by lukeharlandd — COMMENTED** [review]
license

**Pull request closed without merging**
